# 1. Calcular una distancia XX entre dos conjuntos
# 2. Tarea para calcular distancias entre provincias todas vs todas
# 3. Tarea para calcular distancias entre departamentos todos vs todos

tasks:
  # root task: get data #1:
  - source: tasks.get.get_surnames_2015
    name: get-surnames-2015
    product: _products/get/surnames-2015.parquet

  # root task: get data #2:
  - source: tasks.get.get_surnames_2021
    name: get-surnames-2021
    product: _products/get/surnames-2021.parquet

  # Divisional tasks:
  # National:
  - source: tasks.national.national_isonymy.get_national_isonymy_2015
    name: get-national-isonymy-2015
    product: _products/national/isonymy-2015.parquet

  # Regional
  - source: tasks.regional.regional_isonymy.get_regional_isonymy_2015
    name: get-regional-isonymy-2015
    product: _products/regional/isonymy-2015.parquet

  # Provincial
  - source: tasks.provincial.indicators.get_provincial_isonymy_2015
    name: get-provincial-isonymy-2015
    product: _products/provincial/isonymy-2015.parquet

  - source: tasks.provincial.indicators.get_provincial_karlin_macgregor_2015
    name: get-provincial-karlin-macgregor-2015
    product: _products/provincial/karlin-macgregor-2015.parquet

  - source: tasks.provincial.indicators.get_provincial_wright_2015
    name: get-provincial-wright-2015
    product: _products/provincial/wright-2015.parquet

  - source: tasks.provincial.indicators.get_isonymy_and_migration_indicators_2015
    name: get-provincial-merged-indicators-2015
    product: _products/provincial/merged-indicators-2015.parquet

  - source: tasks.provincial.indicators.get_provincial_isonymy_2021
    name: get-provincial-isonymy-2021
    product: _products/provincial/isonymy-2021.parquet

  - source: tasks.provincial.indicators.get_provincial_karlin_macgregor_2021
    name: get-provincial-karlin-macgregor-2021
    product: _products/provincial/karlin-macgregor-2021.parquet

  - source: tasks.provincial.indicators.get_provincial_wright_2021
    name: get-provincial-wright-2021
    product: _products/provincial/wright-2021.parquet

  - source: tasks.provincial.indicators.get_isonymy_and_migration_indicators_2021
    name: get-provincial-merged-indicators-2021
    product: _products/provincial/merged-indicators-2021.parquet

  ## Departmental tasks:
  # Data
  - source: tasks.departmental.isonymy.get_departmental_isonymy_2015
    name: get-departmental-isonymy-2015
    product: _products/departmental/isonymy-2015.parquet

  - source: tasks.departmental.isonymy.get_departmental_isonymy_2021
    name: get-departmental-isonymy-2021
    product: _products/departmental/isonymy-2021.parquet

  - source: tasks.departmental.karlin_mcgregor.get_departmental_karlin_mcgregor_2001
    name: get-departmental-karlin-mcgregor-2001
    product: _products/departmental/karlin-mcgregor-2001.parquet

  - source: tasks.departmental.karlin_mcgregor.get_departmental_karlin_mcgregor_2015
    name: get-departmental-karlin-mcgregor-2015
    product: _products/departmental/karlin-mcgregor-2015.parquet

  - source: tasks.departmental.karlin_mcgregor.get_departmental_karlin_mcgregor_2021
    name: get-departmental-karlin-mcgregor-2021
    product: _products/departmental/karlin-mcgregor-2021.parquet

  - source: tasks.departmental.wright.get_departmental_wright_m_2001
    name: get-departmental-wright-m-2001
    product: _products/departmental/wright-2001.parquet

  - source: tasks.departmental.wright.get_departmental_wright_m_2015
    name: get-departmental-wright-m-2015
    product: _products/departmental/wright-2015.parquet

  - source: tasks.departmental.wright.get_departmental_wright_m_2021
    name: get-departmental-wright-m-2021
    product: _products/departmental/wright-2021.parquet

  # Combine departmental data
  - source: tasks.departmental.merge.get_isonymy_and_migration_indicators_2001
    name: get-merged-indicators-2001
    product: _products/departmental/merged-indicators-2001.parquet

  - source: tasks.departmental.merge.get_isonymy_and_migration_indicators_2015
    name: get-merged-indicators-2015
    product: _products/departmental/merged-indicators-2015.parquet

  - source: tasks.departmental.merge.get_isonymy_and_migration_indicators_2021
    name: get-merged-indicators-2021
    product: _products/departmental/merged-indicators-2021.parquet

  # VIS:
  - source: tasks.departmental.vis.choropleths.plot_comparative_choropleth_maps
    name: plot-departmental-comparative-choropleth-maps-[[divisionalView]]-[[plotColumn]]
    product: _products/departmental/vis-choropleth/[[divisionalView]]/choropleth-[[plotColumn]]-[[divisionalView]].png
    params:
      departmentShapePath: "{{DEPARTMENTS_MINIMAL_SHAPE_PATH}}"
    grid:
      divisionalView: "{{divisional_list}}"
      plotColumn: ["fst", "a", "b", "fishers_alpha", "v", "m"]

  - source: tasks.provincial.vis.choropleths.plot_comparative_choropleth_maps
    name: plot-provincial-comparative-choropleth-maps-[[regionalView]]-[[plotColumn]]
    product: _products/provincial/vis-choropleth/[[regionalView]]/choropleth-[[plotColumn]]-[[regionalView]].png
    params:
      provincialShapePath: "{{PROVINCES_SHAPE_PATH}}"
    grid:
      regionalView: ["Argentina", "Patagonia", "NOA", "NEA", "Centro", "Cuyo"]
      plotColumn: ["fst", "a", "b", "fishers_alpha", "v", "m"]

  - source: tasks.national.vis.ocurrences.get_ocurrences_log_plot_2015
    name: get-national-ocurrences-log-plot-2015
    product: _products/national/vis/ocurrences/ocurrences-log-plot-2015.png

  - source: tasks.regional.vis.ocurrences.get_ocurrences_log_plot_2015
    name: get-regional-ocurrences-log-plot-2015-[[region]]
    product: _products/regional/vis/ocurrences/log-plot-[[region]]-2015.png
    grid:
      region: ["Patagonia", "NOA", "NEA", "Centro", "Cuyo"]

  - source: tasks.provincial.vis.ocurrences.get_ocurrences_log_plot_2015
    name: get-provincial-ocurrences-log-plot-2015-[[province]]
    product: _products/provincial/vis/ocurrences/log-plot-[[province]]-2015.png
    grid:
      province: "{{provincial_list}}"

  - source: tasks.provincial.vis.ocurrences.get_ocurrences_log_plot_2021
    name: get-provincial-ocurrences-log-plot-2021-[[province]]
    product: _products/provincial/vis/ocurrences/log-plot-[[province]]-2021.png
    grid:
      province: "{{provincial_list}}"

  - source: tasks.national.vis.ocurrences.get_ocurrences_log_plot_2021
    name: get-national-ocurrences-log-plot-2021
    product: _products/national/vis/ocurrences/ocurrences-log-plot-2021.png

  - source: tasks.regional.vis.ocurrences.get_ocurrences_log_plot_2021
    name: get-regional-ocurrences-log-plot-2021-[[region]]
    product: _products/regional/vis/ocurrences/log-plot-[[region]]-2021.png
    grid:
      region: ["Patagonia", "NOA", "NEA", "Centro", "Cuyo"]

  # Linear Regressions:
  - source: tasks.regional.linear_regression.get_linear_regression_params_2015
    name: get-regional-linear-regression-params-2015
    product: _products/regional/linear-regression-params-2015.parquet

  - source: tasks.departmental.linear_regression.get_linear_regression_params_2015
    name: get-departmental-linear-regression-params-2015
    product: _products/departmental/linear-regression-params-2015.parquet

  - source: tasks.provincial.linear_regression.get_linear_regression_params_2015
    name: get-provincial-linear-regression-params-2015
    product: _products/provincial/linear-regression-params-2015.parquet
