# 1. Calcular una distancia XX entre dos conjuntos
# 2. Tarea para calcular distancias entre provincias todas vs todas
# 3. Tarea para calcular distancias entre departamentos todos vs todos

tasks:
  # Divisional tasks:
  # National:
  - source: tasks.national.national_isonymy.get_national_isonymy_2015
    name: get-national-isonymy-2015
    product: _products/national/isonymy-2015.parquet

  - source: tasks.regional.regional_isonymy.get_regional_isonymy_2015
    name: get-regional-isonymy-2015
    product: _products/regional/isonymy-2015.parquet

  - source: tasks.provincial.provincial_isonymy.get_provincial_isonymy_2015
    name: get-provincial-isonymy-2015
    product: _products/provincial/isonymy-2015.parquet

  ## Departmental tasks:
  - source: tasks.departmental.isonymy.get_departmental_isonymy_2015
    name: get-departmental-isonymy-2015
    product: _products/departmental/isonymy-2015.parquet

  - source: tasks.departmental.isonymy.get_departmental_isonymy_2021
    name: get-departmental-isonymy-2021
    product: _products/departmental/isonymy-2021.parquet

  - source: tasks.departmental.karlin_mcgregor.get_karlin_mcgregor_departmental_2001
    name: get-karlin-mcgregor-departmental-2001
    product: _products/departmental/karlin-mcgregor-2001.parquet

  - source: tasks.departmental.karlin_mcgregor.get_departmental_karlin_mcgregor_2015
    name: get-departmental-karlin-mcgregor-2015
    product: _products/departmental/karlin-mcgregor-2015.parquet

  - source: tasks.departmental.karlin_mcgregor.get_departmental_karlin_mcgregor_2021
    name: get-departmental-karlin-mcgregor-2021
    product: _products/departmental/karlin-mcgregor-2021.parquet

  - source: tasks.departmental.wright.get_wright_m_departmental_2001
    name: get-wright-m-departmental-2001
    product: _products/departmental/wright-2001.parquet

  - source: tasks.departmental.wright.get_departmental_wright_m_2015
    name: get-departmental-wright-m-2015
    product: _products/departmental/wright-2015.parquet

  - source: tasks.departmental.wright.get_departmental_wright_m_2021
    name: get-departmental-wright-m-2021
    product: _products/departmental/wright-2021.parquet

  - source: tasks.departmental.merge.get_isonymy_and_migration_indicators_2015
    name: get-merged-indicators-2015
    product: _products/departmental/get-merged-indicators-2015.parquet

  - source: tasks.departmental.merge.get_isonymy_and_migration_indicators_2021
    name: get-merged-indicators-2021
    product: _products/departmental/get-merged-indicators-2021.parquet
