# 1. Calcular una distancia XX entre dos conjuntos
# 2. Tarea para calcular distancias entre provincias todas vs todas
# 3. Tarea para calcular distancias entre departamentos todos vs todos

tasks:
  # surname distance task:
  #- source: tasks.distances.get_dapartamental_distances
  #  name: get_dapartamental_distances
  #  product: 
  #    isonymic: _products/distance_matrices/dapartamental_isonymic.parquet
  #    lasker: _products/distance_matrices/dapartamental_lasker.parquet
  #    nei: _products/distance_matrices/dapartamental_nei.parquet
  #    euclidean: _products/distance_matrices/dapartamental_euclidean.parquet
 
  # geografical distance task:
  #- source: tasks.distances.get_dapartamental_distances_in_meters
  #  name: get_dapartamental_distances_in_meters
  #  params:
  #    departments_shape_file: '{{DEPARTMENTS_SHAPE_PATH}}'
  #  product: _products/distance_matrices/dapartamental_in_meters.parquet


  # fisher and karlin-mcgregor
  # |
  # - departments:
  #   |
  #   - 2000:
  - source: tasks.migration_indicators.get_karlin_mcgregor_departamental_2001
    name: get-karlin-mcgregor-departamental-2001
    product: _products/migration-indicators/karlin-mcgregor-departamental-2001.parquet
  - source: tasks.migration_indicators.get_wright_m_departaments_2001
    name: get-wright-m-departaments-2001
    product: _products/migration-indicators/wright-m-departaments-2001.parquet
  #   |
  #   - 2015:
  - source: tasks.migration_indicators.get_karlin_mcgregor_departamental_2015
    name: get-karlin-mcgregor-departamental-2015
    product: _products/migration-indicators/karlin-mcgregor-departamental-2015.parquet
  
  - source: tasks.migration_indicators.get_wright_m_departaments_2015
    name: get-wright-m-departaments-2015
    product: _products/migration-indicators/wright-m-departaments-2015.parquet
  #   |
  #   - 2021:
  - source: tasks.migration_indicators.get_karlin_mcgregor_departamental_2021
    name: get-karlin-mcgregor-departamental-2021
    product: _products/migration-indicators/karlin-mcgregor-departamental-2021.parquet

  - source: tasks.migration_indicators.get_wright_m_departaments_2021
    name: get-wright-m-departaments-2021
    product: _products/migration-indicators/wright-m-departaments-2021.parquet

  # |
  # - circuits:
  #   |
  #   - 2021:
  # TODO: Descomentar (comente porque le cambié la carpeta de destino)
  # - source: tasks.migration_indicators.get_karlin_mcgregor_circuito_2021
  #   name: get-karlin-mcgregor-circuito-2021
  #   product: _products/migration-indicators/karlin-mcgregor-circuitos-2021.parquet

  # vis
  - source: tasks.vis.choroplets.plot_choroplet_compartive_map
    name: plot-choroplet-compartive-map
    params:
      departmentShapePath: '{{DEPARTMENTS_SHAPE_PATH}}'
    product: _products/vis/choroplet/karlin-mcgregor-departamental-2001-2021.png
  
  - source: tasks.vis.choroplets.plot_choroplet_compartive_map_wright_m
    name: plot-choroplet-compartive-map-wright-m
    params:
      departmentShapePath: '{{DEPARTMENTS_SHAPE_PATH}}'
    product: _products/vis/choroplet/wright-m-departamental-2001-2021.png
  
  - source: tasks.vis.maps.plot_karlin_mcgregor_2015
    name: plot-karlin-mcgregor-2015
    params:
      shape_path: '{{DEPARTMENTS_SHAPE_PATH}}'
    product:
      map-v: _products/vis/map-karlin-mcgregor-departamental.png
      map-a: _products/vis/map-fishers-alpha-departamental.png
      scatterplot-a-and-v: _products/vis/scatterplot-karlin-mcgregor-and-fishers-alpha-departamental.png

  - source: tasks.vis.choroplets.plot_choroplet_comparative_maps
    name: plot-choroplet-comparative-maps-[[region_name]]-[[work_column]]
    product: _products/vis/choroplet/comparative-choropleth-[[region_name]]-[[work_column]].png
    params:
      departmentShapePath: '{{DEPARTMENTS_MINIMAL_SHAPE_PATH}}'
    grid:
        region_name: ["NOA", "NEA", "Centro", "Cuyo", "Patagonia"]
        work_column: ['m_100', 'fst']

  # Report:
  - source: tasks.reports.create_report
    name: create-report
    product: _output/report.pdf

  # Isonymics
  - source: tasks.isonymic_indicators.get_isonymy_departments_2015
    name: get-isonymy-departments-2015
    product: _products/isonymy/isonymy-departments-2015.parquet

  - source: tasks.isonymic_indicators.get_isonymy_departments_2021
    name: get-isonymy-departments-2021
    product: _products/isonymy/isonymy-departments-2021.parquet
